### ISSUE TITLE
API coverage checklist

### ISSUE THREAD

**Issue by not-so-smart** [not-so-smart/node-groupme#1]
# Current state of API coverage

## Groups
- [ ] Get active groups
- [ ] Get former groups
- [ ] Get single group by ID
- [ ] Create group
- [ ] Update group
- [ ] Delete group
- [ ] Join group
- [ ] Rejoin former group
- [ ] Transfer ownership
### Group Messages
- [ ] Get messages
- [ ] Send message
- [ ] Delete message

## Members
- [ ] Add members
- [ ] Subtask: Fetch results of Add members
- [ ] Remove member
- [ ] Change nickname

## Chats
- [ ] Get chats
### Chat Messages
- [ ] Get messages
- [ ] Send message
- [ ] Delete message

## Users
- [ ] Get all blocks
- [ ] Check for block from other user
- [ ] Block user
- [ ] Unblock user

## Likes
- [ ] Like message
- [ ] Unlike message
- [ ] Get leaderboard
- [ ] Get given likes
- [ ] Get received likes

## Calendar
- [ ] Get events
- [ ] Create event
- [ ] Update event
- [ ] Delete event
- [ ] Add RSVP
- [ ] Undo RSVP

## Account
- [ ] Get details
- [ ] Update details
- [ ] Enable SMS
- [ ] Disable SMS

## Polls
- [ ] Create poll
- [ ] Get all polls
- [ ] Get poll by ID
- [ ] Vote
- [ ] End poll

## Attachments
- [ ] Upload image
- [ ] Upload video

## Push
- [ ] figure out how push works

## Bots (ignored for now)

**Comment by AlureonTheVirus** [comment]
not that I can speak for the project but I'd like to add that groupme has also added subgroups as what it calls "topics". 

I assume that we will want to have websocket support at some point built in. A more Event-Driven approach would make bot development with this library a lot simpler and more straightforward/intuitive. (Let me know if I'm wrong and that's already implemented.)

It also seems that this project lacks a lot of in depth documentation and examples that other API wrappers typically have. (Not a diss, just an observation and possibly another goal to work towards.)

**Comment by not-so-smart** [comment]
> not that I can speak for the project but I'd like to add that groupme has also added subgroups as what it calls "topics".

Thank you! Yes, we do want to add support for topics, currently there is no framework for it but feel free to open a PR if you'd like to get that started :)

> I assume that we will want to have websocket support at some point built in. A more Event-Driven approach would make bot development with this library a lot simpler and more straightforward/intuitive. (Let me know if I'm wrong and that's already implemented.)

Good news! The PR for websockets (#104) is currently open and will be merged soon! :D

> It also seems that this project lacks a lot of in depth documentation and examples that other API wrappers typically have. (Not a diss, just an observation and possibly another goal to work towards.)

Yes, as you can see from this checklist, a lot of the framework (files, classes and method stubs to shape the relevant data structures) and even most of the implementation (filling in those method stubs with code that interacts with the API) is currently missing. API coverage is a slightly higher priority than documentation at this stage, but we do have docs at https://groupme.js.org/ which are automatically generated on each release and built from TS type information (for classes and their properties) along with any JSdoc comments present in the code (for descriptions of these objects and example usage). If you want to add to this documentation, just open a PR adding comments following the JSdoc standard (https://jsdoc.app/) and they'll be added to the generated docs in the next build.
